config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :airports

  root to: 'flights#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/airport.rb
class Airport < ApplicationRecord

  belongs_to :origin, class_name: :Airport
  belongs_to :destination, class_name: :Airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :departing_flights,
    class_name: :Flight,
    foreign_key: :depart_id,
    dependent: :destroy

  has_many :arriving_flights,
    class_name: :Flight,
    foreign_key: :arrival_id,
    dependent: :destroy

  def self.search(search)
    if search
      where(["depart_id LIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: %i[ show edit update destroy ]

  # GET /airports or /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1 or /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports or /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to airport_url(@airport), notice: "Airport was successfully created." }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1 or /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to airport_url(@airport), notice: "Airport was successfully updated." }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1 or /airports/1.json
  def destroy
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to airports_url, notice: "Airport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.require(:airport).permit(:airport_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    @flights = Flight.search(params[:search])
    @depart_id = Flight.all.map { |o| [o.depart_id, o.id] }
    @arrival_id = Flight.all.map { |a| [a.arrival_id, a.id] }
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flight_url(@flight), notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy

    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:depart_id, :arrival_id, :date, :flight_duration, :search)
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/airports/_airport.html.erb
<div id="<%= dom_id airport %>">
  <p>
    <strong>Airport code:</strong>
    <%= airport.airport_code %>
  </p>

</div>

app/views/airports/_form.html.erb
<%= form_with(model: airport) do |form| %>
  <% if airport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
        <% airport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :airport_code, style: "display: block" %>
    <%= form.text_field :airport_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Show this airport", @airport %> |
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Airports</h1>

<div id="airports">
  <% @airports.each do |airport| %>
    <%= render airport %>
    <p>
      <%= link_to "Show this airport", airport %>
    </p>
  <% end %>
</div>

<%= link_to "New airport", new_airport_path %>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @airport %>

<div>
  <%= link_to "Edit this airport", edit_airport_path(@airport) %> |
  <%= link_to "Back to airports", airports_path %>

  <%= button_to "Destroy this airport", @airport, method: :delete %>
</div>

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>Depart:</strong>
    <%= flight.depart_id %>
  </p>

  <p>
    <strong>Arrival:</strong>
    <%= flight.arrival_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= flight.date %>
  </p>

  <p>
    <strong>Flight duration:</strong>
    <%= flight.flight_duration %>
  </p>

</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :depart_id, style: "display: block" %>
    <%= form.text_field :depart_id %>
  </div>

  <div>
    <%= form.label :arrival_id, style: "display: block" %>
    <%= form.text_field :arrival_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :flight_duration, style: "display: block" %>
    <%= form.number_field :flight_duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Show this flight", @flight %> |
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flights</h1>

<%= form_with(url:"/flights", method: 'get', local: true) do |f| %>
  <% f.label :search, 'Search by Depart ID' %>
  <%= f.text_field(:search) %>

  <%= f.submit "Search"%>
<% end %>


<%= form_with(url:"/flights", method: 'get', local: true) do |f| %>
  <%= f.label "Arrival ID"%>
  <%= f.select(:arrival_id, options_for_select(@arrival_id, params[:arrival_id])) %>
  
  <br>
  <%= f.label "Depart ID"%>
  <%= f.select(:depart_id, options_for_select(@depart_id, params[:depart_id])) %>
  <br>
  <%= f.date_field(:date) %>
  <br>
  <%= f.label "Passengers"%>
  <%= f.select(:Passengers, options_for_select([1,2,3,4]))%>
  <%= f.submit "Search"%>
<% end %>



<div id="flights">
  <% @flights.each do |flight| %>
    <!--<%= render flight %> -->
    <p>
      <%= render flight %>
      
      <%= link_to "Show this flight", flight %>
    </p>
    
    
  <% end %>
</div>

<%= link_to "New flight", new_flight_path %>

app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render "form", flight: @flight %>

<br>

<div>
  <%= link_to "Back to flights", flights_path %>
</div>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%= link_to "Edit this flight", edit_flight_path(@flight) %> |
  <%= link_to "Back to flights", flights_path %>

  <%= button_to "Destroy this flight", @flight, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>